### ISSUE TITLE
pfab conditions should show first part of the unified_question

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#101]
In the pfab conditions we should show:

> Imagine a group of **prevalence_02_variable** women at age **age_variable** that go through a massive screening. 

Should look:

> Imagine a group of **prevalence_02_variable** women at age **age_variable** that go through a massive screening.
> 
> ____ women receive a positive test_result that correctly indicates the presence of medical_condition, and ____ women receive a positive test_result that incorrectly indicates the presence of medical_condition. Therefore, given that the test_result indicates the signs of medical_condition, the probability that person_01 actually has medical_condition is ____ out of ____

**Comment by nik0lai** [comment]
Is not so simple to achieve this.
Right now the PPV question is a separate question on Qualtrics that is displayed in every condition, except when the presentation format is "positive framework" and the response type is "sequential guided". The reason is that the question contains calls to Embedded data fields, this calls cannot be stored inside embedded data fields.

If you want the following, there is no way to show only the first or both sentences.

> Imagine a group of 2000 women at age 20/40 that go through a routine screening. Of those with a positive mammogram/test result, how many would you expect to actually have breast cancer/Down's syndrome?

The other solution is to separate the first and second sentence in two text items, which result in this.

![image](https://user-images.githubusercontent.com/11561730/46316943-f119a480-c5a7-11e8-8688-86a3f8774211.png)

Another solution would be to create the PPV question using Javascript and conditionals according to what presentation format and response type is being displayed.

**Comment by nik0lai** [comment]
we're using the two parts ppv question now.
it is necessary to modify display logic of this questions on manual changes section.

**Comment by nik0lai** [comment]
fixed.
